@startuml
!pragma layout smetana

abstract class Animal {

}

class Lion {

}

class Wolf {

}

class Rabbit {

}

class Contest {

}

Animal <|-- Lion : IS-A
Animal <|-- Wolf : IS-A
Animal <|-- Rabbit : IS-A

Contest *-- Animal : HAS-A

@enduml